// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EthicStance } from "./EthicStance";

export type FactionEthics = { violence: EthicStance, expansion: EthicStance, trade: EthicStance, tradition: EthicStance, mercy: EthicStance, };
