// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiplomaticState } from "./DiplomaticState";

export type FactionRelationship = { factionA: string, factionB: string, opinion: number, animosity: number, state: DiplomaticState, };
