// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactionEthics } from "./FactionEthics";
import type { InterestGroup } from "./InterestGroup";

export type Faction = { id: string, name: string, color: string, aggression: number, settlements: Array<string>, population: number, stability: number, wealth: number, military: number, culture: number, techLevel: number, ethics: FactionEthics, leaderId: string | null, interestGroups: Array<InterestGroup>, innovations: Array<string>, };
