// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatDelta } from "./StatDelta";

export type GameEvent = { id: string, tick: number, year: number, secondsOffset: number, subject: string, action: string, object: string, causedBy: string | null, significance: number, playerCaused: boolean, description: string, motivation: string, statDeltas: Array<StatDelta>, };
