// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tile } from "./Tile";

export type GameMap = { width: number, height: number, tiles: Array<Array<Tile>>, };
