// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoricalFigureRole } from "./HistoricalFigureRole";
import type { HistoricalFigureValues } from "./HistoricalFigureValues";
import type { RulerTrait } from "./RulerTrait";

export type HistoricalFigure = { id: string, name: string, factionId: string, role: HistoricalFigureRole, values: HistoricalFigureValues, traits: Array<RulerTrait>, bornYear: number, diedYear: number | null, legitimacy: number, };
