// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

export type HolySite = { id: string, name: string, position: Position, religionId: string, };
