// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InnovationType } from "./InnovationType";

export type Innovation = { id: string, name: string, type: InnovationType, description: string, originYear: number, originSettlementId: string, };
