// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterestGroupType } from "./InterestGroupType";
import type { PartialFactionEthics } from "./PartialFactionEthics";

export type InterestGroup = { id: string, name: string, type: InterestGroupType, power: number, ethicsBias: PartialFactionEthics, };
