// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemHistoryEntry } from "./ItemHistoryEntry";
import type { ItemType } from "./ItemType";
import type { Position } from "./Position";

export type Item = { id: string, name: string, description: string, type: ItemType, significance: number, position: Position, history: Array<ItemHistoryEntry>, };
