// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KnowledgeEntry = { eventId: string, source: string, factionPerspective: string, text: string, discoveredYear: number, };
