// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NPCKnowledge } from "./NPCKnowledge";
import type { NPCPersonality } from "./NPCPersonality";
import type { Position } from "./Position";

export type NPC = { id: string, name: string, position: Position, factionId: string, personality: NPCPersonality, knowledge: Array<NPCKnowledge>, dialogueKey: string, alive: boolean, };
