// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EthicStance } from "./EthicStance";

export type PartialFactionEthics = { violence: EthicStance | null, expansion: EthicStance | null, trade: EthicStance | null, tradition: EthicStance | null, mercy: EthicStance | null, };
