// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";
import type { KnowledgeEntry } from "./KnowledgeEntry";
import type { Position } from "./Position";

export type Player = { id: string, name: string, position: Position, inventory: Array<Item>, knowledgeLog: Array<KnowledgeEntry>, actionsThisEra: Array<string>, insight: number, };
