// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReligionTenet } from "./ReligionTenet";

export type Religion = { id: string, name: string, founderId: string | null, originSettlementId: string, tenets: Array<ReligionTenet>, color: string, };
