// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { ResourceNodeType } from "./ResourceNodeType";

export type ResourceNode = { id: string, type: ResourceNodeType, position: Position, value: number, };
