// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaithPressure } from "./FaithPressure";
import type { Position } from "./Position";

export type Settlement = { id: string, name: string, position: Position, factionId: string, npcs: Array<string>, items: Array<string>, faith: Array<FaithPressure>, dominantReligionId: string | null, innovations: Array<string>, };
