// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimConfig = { schismProbability: number, techDiffusionRate: number, tradeDecayRate: number, tradeGrowthRate: number, };
