// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactionStatKey } from "./FactionStatKey";

export type StatDelta = { factionId: string, stat: FactionStatKey, delta: number, };
