// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CooldownEntry } from "./CooldownEntry";
import type { StorytellerMode } from "./StorytellerMode";

export type StorytellerState = { mode: StorytellerMode, tension: number, tensionDecayRate: number, tensionFloor: number, spotlightFactionId: string | null, spotlightSetYear: number, spotlightDecayYears: number, yearsSincePlayerDiscovery: number, debtInterventionsFired: number, cooldowns: Array<CooldownEntry>, maxEventsPerYear: number, highSigEventsThisYear: number, lastHighSigYear: number, consecutiveQuietYears: number, playerActionCount: number, pendingNotification: string | null, };
