// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileModifier } from "./TileModifier";

export type TileDynamic = { factionId: string | null, settlementId: string | null, modifiers: Array<TileModifier> | null, };
