// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Biome } from "./Biome";
import type { TileModifier } from "./TileModifier";

export type Tile = { biome: Biome, elevation: number, rainfall: number, factionId: string | null, settlementId: string | null, walkable: boolean, modifiers: Array<TileModifier> | null, };
