// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileModifierType } from "./TileModifierType";

export type TileModifier = { type: TileModifierType, duration: number, };
