// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { TradeCommodity } from "./TradeCommodity";

export type TradeRoute = { id: string, startSettlementId: string, endSettlementId: string, path: Array<Position>, volume: number, commodity: TradeCommodity, active: boolean, };
