// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { VisualEffectType } from "./VisualEffectType";

export type VisualEffect = { id: string, type: VisualEffectType, position: Position, startTime: number, duration: number, color: string | null, };
