// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Faction } from "./Faction";
import type { FactionRelationship } from "./FactionRelationship";
import type { GameEvent } from "./GameEvent";
import type { GameMapDynamic } from "./GameMapDynamic";
import type { HistoricalFigure } from "./HistoricalFigure";
import type { HolySite } from "./HolySite";
import type { Innovation } from "./Innovation";
import type { Item } from "./Item";
import type { NPC } from "./NPC";
import type { Player } from "./Player";
import type { Religion } from "./Religion";
import type { ResourceNode } from "./ResourceNode";
import type { Ruin } from "./Ruin";
import type { Settlement } from "./Settlement";
import type { SimConfig } from "./SimConfig";
import type { StorytellerState } from "./StorytellerState";
import type { TradeRoute } from "./TradeRoute";
import type { VisualEffect } from "./VisualEffect";

export type WorldStateDynamic = { seed: number, currentYear: number, map: GameMapDynamic, factions: Array<Faction>, relationships: Array<FactionRelationship>, historicalFigures: Array<HistoricalFigure>, settlements: Array<Settlement>, ruins: Array<Ruin>, resourceNodes: Array<ResourceNode>, npcs: Array<NPC>, items: Array<Item>, tradeRoutes: Array<TradeRoute>, religions: Array<Religion>, holySites: Array<HolySite>, innovations: Array<Innovation>, events: Array<GameEvent>, player: Player, storyteller: StorytellerState, visuals: Array<VisualEffect>, simConfig: SimConfig | null, };
